# Generated by Django 4.1.4 on 2023-12-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_ime', models.CharField(max_length=30)),
                ('prof_prezime', models.CharField(max_length=30)),
                ('prof_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
